master_factory_base_path: kseg
template_path: yaml_templates
name: maeref-l16-u160k-uper
stage_name: ade20k


vars:
  batch_size: 16
  updates: 160000
  optim:
    kind: adamw
    lr: 2.0e-5
    betas: [ 0.9, 0.999 ]
    weight_decay: 0.05
    schedule:
      kind: linear_warmup_cosine_decay_schedule
      warmup_updates: 1500
      end_value: 1.0e-6
    lr_scaler:
      kind: linear_lr_scaler
      divisor: 16


datasets:
  train:
    kind: datasets.ade20k
    split: training
    sample_wrappers:
      - kind: segmentation_transform_wrapper
        transform:
          - kind: segmentation_random_resize
            ratio_resolution: [ 2048, 512 ]
            ratio_range: [ 0.5, 2.0 ]
            interpolation: bicubic
          - kind: segmentation_random_crop
            size: 512
            max_category_ratio: 0.75
            ignore_index: -1
          - kind: segmentation_random_horizontal_flip
      - kind: x_transform_wrapper
        transform:
          - kind: color_jitter
            brightness: 0.5
            contrast: 0.5
            saturation: 0.5
            hue: 0.25
          - kind: imagenet1k_norm
      - kind: segmentation_transform_wrapper
        transform:
          - kind: segmentation_pad
            size: 512
            fill: -1
  val:
    kind: datasets.ade20k
    split: validation
    sample_wrappers:
      - kind: x_transform_wrapper
        transform:
          - kind: imagenet1k_norm

model:
  kind: composite.vit_upernet
  encoder:
    kind: encoders.vit
#    patch_size: 16
#    kwargs: ${select:small:${yaml:models/vit}}
    use_last_norm: false
    drop_path_rate: 0.2
    drop_path_decay: true
    layerscale: 1.0
    optim:
      template: ${vars.optim}
      template.param_group_modifiers:
        - kind: optim.layerwise_lr_decay
          layerwise_lr_decay: 0.95
    initializers:
      - kind: torchhub_vit_initializer
        repo: BenediktAlkin/torchhub-ssl
        model: in1k_mae_l16_refined
        use_checkpoint_kwargs: true
  postprocessor:
    kind: postprocessors.vit_postprocessor
    optim: ${vars.optim}
  auxiliary:
    kind: heads.upernet_auxiliary
    dim: 256
    dropout: 0.1
    feature_index: 2
    optim: ${vars.optim}
  decoder:
    kind: heads.upernet_decoder
    pool_scales: [ 1, 2, 3, 6 ]
    dropout: 0.1
    optim: ${vars.optim}

trainer:
  kind: segmentation_trainer
  precision: bfloat16
  backup_precision: float32
  effective_batch_size: ${vars.batch_size}
  max_updates: ${vars.updates}
  ignore_index: -1
  loss_weights:
    auxiliary: 0.4
  log_every_n_updates: 1000
  skip_nan_loss: true
  callbacks:
    # resume
    - kind: checkpoint_callback
      every_n_epochs: 10
      save_weights: false
      save_latest_weights: true
      save_latest_optim: true
    # miou
    - kind: offline_segmentation_callback
      every_n_updates: 10000
      batch_size: 1
      dataset_key: val
      ignore_index: -1
      mode: slide
      mode_kwargs:
        stride: [ 341, 341 ]
    # best checkpoint
    - kind: best_checkpoint_callback
      every_n_updates: 10000
      metric_key: iou/val/main